name: Release

# Triggered only when a tag is pushed
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Release the application
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
